declare namespace NodeJS {
  interface ProcessEnv {
    //Global
    REACT_APP_BASE_URL_MOVIE: string;
    REACT_APP_LOCALSTORAGE_USER_INFO: string;
    REACT_APP_TOKEN_CYBERSOFT: string;

    //Rap
    REACT_APP_MA_HE_THONG_RAP_BHDSTAR: string;
    REACT_APP_MA_HE_THONG_RAP_CGV: string;
    REACT_APP_MA_HE_THONG_RAP_CINESTAR: string;
    REACT_APP_MA_HE_THONG_RAP_GALAXY: string;
    REACT_APP_MA_HE_THONG_RAP_LOTTECINIMA: string;
    REACT_APP_MA_HE_THONG_RAP_MEGAS: string;

    //Nhom
    REACT_APP_MA_NHOM_GP01: string;
    REACT_APP_MA_NHOM_GP02: string;
    REACT_APP_MA_NHOM_GP03: string;
    REACT_APP_MA_NHOM_GP04: string;
    REACT_APP_MA_NHOM_GP05: string;
    REACT_APP_MA_NHOM_GP06: string;
    REACT_APP_MA_NHOM_GP07: string;
    REACT_APP_MA_NHOM_GP08: string;
    REACT_APP_MA_NHOM_GP09: string;

    //Nguoi Dung
    REACT_APP_MA_LOAI_NGUOI_DUNG_KHACH_HANG: string;
    REACT_APP_MA_LOAI_NGUOI_DUNG_QUAN_TRI: string;

    //Router App
    REACT_APP_LINK_HOME: string;
    REACT_APP_LINK_CONTACT: string;
    REACT_APP_LINK_NEWS: string;
    REACT_APP_LINK_DETAIL: string;
    REACT_APP_LINK_SIGN_UP: string;
    REACT_APP_LINK_SIGN_IN: string;
    REACT_APP_LINK_CHECK_OUT: string;
    REACT_APP_LINK_PROFILE: string;
    REACT_APP_LINK_ADMIN_DASHBOARD: string;
    REACT_APP_LINK_ADMIN_FILMS: string;
    REACT_APP_LINK_ADMIN_SHOWTIME_FILMS: string;
    REACT_APP_LINK_ADMIN_ADD_FILMS: string;
    REACT_APP_LINK_ADMIN_EDIT_FILMS: string;
    REACT_APP_LINK_ADMIN_EDIT_USERMANAGER: string;

    //Router Service :string
    REACT_APP_LINK_QUAN_LY_PHIM: string;
    REACT_APP_LINK_QUAN_LY_PHIM_XP: string;
    REACT_APP_LINK_QUAN_LY_PHIM_XOA_PHIM: string;
    REACT_APP_LINK_QUAN_LY_PHIM_LAY_DANH_SACH_BANNER: string;
    REACT_APP_LINK_QUAN_LY_PHIM_LAY_DANH_SACH_PHIM: string;
    REACT_APP_LINK_QUAN_LY_PHIM_LAY_DANH_SACH_PHIM_PHAN_TRANG: string;
    REACT_APP_LINK_QUAN_LY_PHIM_LAY_DANH_PHIM_THEO_NGAY: string;
    REACT_APP_LINK_QUAN_LY_PHIM_LAY_THONG_TIN_PHIM: string;
    REACT_APP_LINK_QUAN_LY_PHIM_THEM_PHIM_UP_LOAD_HINH: string;
    REACT_APP_LINK_QUAN_LY_PHIM_CAP_NHAT_PHIM_UPLOAD: string;
    REACT_APP_LINK_QUAN_LY_PHIM_CAP_NHAT_PHIM_UPLOAD: string;

    //Router Service QuanNguoiDung
    REACT_APP_LINK_QUAN_LY_NGUOI_DUNG_DANG_NHAP: string;
    REACT_APP_LINK_QUAN_LY_NGUOI_DUNG_DANG_KY: string;
    REACT_APP_LINK_QUAN_LY_NGUOI_DUNG_LAY_DANH_SACH_LOAI_NGUOI_DUNG: string;
    REACT_APP_LINK_QUAN_LY_NGUOI_DUNG_LAY_DANH_SACH_NGUOI_DUNG: string;
    REACT_APP_LINK_QUAN_LY_NGUOI_DUNG_QUAN_LY_NGUOI_DUNG: string;
    REACT_APP_LINK_QUAN_LY_NGUOI_DUNG_LAY_DANH_SACH_NGUOI_DUNG_PHAN_TRANG: string;
    REACT_APP_LINK_QUAN_LY_NGUOI_DUNG_TIM_KIEM_NGUOI_DUNG: string;
    REACT_APP_LINK_QUAN_LY_NGUOI_DUNG_TIM_KIEM_NGUOI_DUNG_PHAN_TRANG: string;
    REACT_APP_LINK_QUAN_LY_NGUOI_DUNG_THONG_TIN_TAI_KHOAN: string;
    REACT_APP_LINK_QUAN_LY_NGUOI_DUNG_XOA_NGUOI_DUNG: string;
    REACT_APP_LINK_QUAN_LY_NGUOI_DUNG_CAP_NHAT_THONG_TIN_NGUOI_DUNG: string;
    REACT_APP_LINK_QUAN_LY_NGUOI_DUNG_THEM_NGUOI_DUNG: string;
    REACT_APP_LINK_QUAN_LY_NGUOI_DUNG_LAY_THONG_TIN_NGUOI_DUNG: string;

    //Router Service QuanDatVe
    REACT_APP_LINK_QUAN_LY_DAT_VE_DAT_VE: string;
    REACT_APP_LINK_QUAN_LY_DAT_VE_TAO_LICH_CHIEU: string;
    REACT_APP_LINK_QUAN_LY_DAT_VE_LAY_DANH_SACH_PHONG_VE: string;

    //Router Service QuanLyRap
    REACT_APP_LINK_QUAN_LY_RAP_LAY_THONG_TIN_HE_THONG_RAP: string;
    REACT_APP_LINK_QUAN_LY_RAP_LAY_THONG_TIN_CUM_RAP_THEO_HE_THONG: string;
    REACT_APP_LINK_QUAN_LY_RAP_LAY_THONG_TIN_LICH_CHIEU_HE_THONG_RAP: string;
    REACT_APP_LINK_QUAN_LY_RAP_LAY_THONG_TIN_LICH_CHIEU_PHIM: string;

    //WebSocket;
    REACT_APP_URL_WEB_SOCKET: string;
    REACT_APP_SOCKET_DAT_GHE: string;
    REACT_APP_SOCKET_HUY_DAT: string;
    REACT_APP_SOCKET_DAT_GHE_THANH_CONG: string;
    REACT_APP_SOCKET_DAT_VE_THANH_CONG: string;
    REACT_APP_SOCKET_LOAD_DANH_SACH_GHE_DA_DAT: string;
    REACT_APP_SOCKET_LOAD_DANH_SACH_GHE: string;
  }
}
